### ISSUE TITLE
Image Builder incorrectly placed in staging nav bar

### ISSUE THREAD

**Issue by jkozol** [RedHatInsights/cloud-services-config#970]
In https://github.com/RedHatInsights/cloud-services-config/blob/stage-beta/main.yml#L457 the Image Builder application is placed under the Operations Insights (`operations`) section of the navigation bar. But, on console.stage.redhat.com/beta/insights, it is not placed in this subgroup. For me, it is just in the main insights nav bar and not in a subgroup. 

![Screenshot from 2021-11-20 23-03-36](https://user-images.githubusercontent.com/11712857/142742184-6cfff8cd-9894-4729-8529-e4a90d6b6ea4.png)

**Comment by Hyperkid123** [comment]
@jkozol is this just a stage-beta environment?

**Comment by jkozol** [comment]
@Hyperkid123 It is only an issue in stage beta. In prod-beta it appears as expected.
